### ISSUE TITLE
Recursos recomendados

### ISSUE THREAD

**Issue by Shinkei** [julianduque/picx#3]
Hola @julianduque,
queria pedirte si tienes algunos recursos recomendados como libros o webs ... etc
Gracias!

**Comment by Shinkei** [comment]
algun update @julianduque ?

**Comment by julianduque** [comment]
@Shinkei Hola! Apenas veo esto!

https://www.manning.com/books/node-js-in-action-second-edition
https://wesbos.com/learn-node/
https://nodeschool.io
https://nodejs.org/en/docs/guides/

Ando preparando un contenido para presentar en Twitch en un mes mas o menos para que estes pendiente.

**Comment by Shinkei** [comment]
Uff rebien, gracias @julianduque :100:
